sudo: false
language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 2.7
          env: TOXENV=qa

install: pip install -U pip tox coveralls
script: tox
after_success:
  - coveralls
